# Generated by Django 4.2.5 on 2023-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0003_choice_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choices",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="choices",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text",
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
