# Generated by Django 4.2.5 on 2023-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0005_alter_choice_choice_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.TextField(default="Write choices here"),
        ),
    ]
