# Generated by Django 4.2.5 on 2023-09-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0007_course_intsructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission_Choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onlinecourse.choice",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onlinecourse.submission",
                    ),
                ),
            ],
        ),
    ]
