# Generated by Django 4.2.5 on 2023-09-15 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0008_submission_choices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course_Intsructor",
            new_name="Course_Instructor",
        ),
    ]
