# Generated by Django 4.2.5 on 2023-09-15 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0009_rename_course_intsructor_course_instructor"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Submission_Choices",
            new_name="Submission_Choice",
        ),
    ]
